version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn hx-requests-demo.wsgi:application --bind 0.0.0.0:8001
    container_name: hx-requests-demo-web
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8001"
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=hx-requests-demo.com
      - LETSENCRYPT_HOST=hx-requests-demo.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - proxy-network

  # static files
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nginx
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=hx-requests-demo.com
      - VIRTUAL_PATH=/static
      - VIRTUAL_PORT=80
    networks:
      - proxy-network
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html:ro  # Ensures static files are shared
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  proxy-network:
    external: true

volumes:
  static_volume:
