version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hx-db
    volumes:
      - hx_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - proxy-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # image: 532288722115.dkr.ecr.us-east-1.amazonaws.com/hx:latest
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8001
    container_name: hx-web
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8001"
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=hx-requests-demo.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=hx-requests-demo.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8001
    networks:
      - proxy-network
    depends_on:
      - db

  # static files
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nginx
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=hx-requests-demo.com
      - VIRTUAL_PATH=/static
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hx-requests-demo.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - proxy-network
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html  # Ensures static files are shared

networks:
  proxy-network:
    external: true

volumes:
  static_volume:
  hx_postgres_data:
